/* Generated by the Nim Compiler v1.9.3 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI33554466 = {size: 0,kind: 1,base: null,node: null,finalizer: null};
var NTI721420302 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI973078608 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI973078614 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555178 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555186 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555185 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555182 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555183 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555183 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555183.node = NNI33555183;
NTI33555185.base = NTI33555182;
NTI33555186.base = NTI33555182;
var NNI33555182 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555185, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555186, name: "up", sons: null}]};
NTI33555182.node = NNI33555182;
var NNI33555178 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555178.node = NNI33555178;
NTI33555182.base = NTI33555178;
NTI33555183.base = NTI33555182;
NTI134217741.base = NTI33555183;
NTI134217743.base = NTI134217741;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555183;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555183;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555183;
var NNI973078614 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "a", len: 0, typ: NTI973078608, name: "a", sons: null}, 
{kind: 1, offset: "b", len: 0, typ: NTI33554435, name: "b", sons: null}]};
NTI973078614.node = NNI973078614;
var NNI721420302 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554435, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554466, name: "Field1", sons: null}]};
NTI721420302.node = NNI721420302;

function mnewString(len_33556956) {
        return new Array(len_33556956);
  

  
}

function toJSStr(s_33556860) {
  var result_33556861 = null;

    var res_33556899 = newSeq_33556878((s_33556860).length);
    var i_33556900 = 0;
    var j_33556901 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556900 < (s_33556860).length)) break Label2;
          var c_33556902 = s_33556860[i_33556900];
          if ((c_33556902 < 128)) {
          res_33556899[j_33556901] = String.fromCharCode(c_33556902);
          i_33556900 += 1;
          }
          else {
            var helper_33556915 = newSeq_33556878(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556916 = c_33556902.toString(16);
                  if ((((code_33556916) == null ? 0 : (code_33556916).length) == 1)) {
                  helper_33556915.push("%0");;
                  }
                  else {
                  helper_33556915.push("%");;
                  }
                  
                  helper_33556915.push(code_33556916);;
                  i_33556900 += 1;
                  if ((((s_33556860).length <= i_33556900) || (s_33556860[i_33556900] < 128))) {
                  break Label3;
                  }
                  
                  c_33556902 = s_33556860[i_33556900];
                }
            };
++excHandler;
            try {
            res_33556899[j_33556901] = decodeURIComponent(helper_33556915.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556899[j_33556901] = helper_33556915.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556901 += 1;
        }
    };
    if (res_33556899.length < j_33556901) { for (var i = res_33556899.length ; i < j_33556901 ; ++i) res_33556899.push(null); }
               else { res_33556899.length = j_33556901; };
    result_33556861 = res_33556899.join("");

  return result_33556861;

}

function raiseException(e_33556648, ename_33556649) {
    e_33556648.name = ename_33556649;
    if ((excHandler == 0)) {
    unhandledException(e_33556648);
    }
    
    throw e_33556648;

  
}

function addInt(a_33557003, b_33557004) {
        var result = a_33557003 + b_33557004;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_33557268, a_33557269, b_33557270) {
  var result_33557271 = 0;

  BeforeRet: {
    if (((a_33557269 <= i_33557268) && (i_33557268 <= b_33557270))) {
    result_33557271 = i_33557268;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557271;

}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_33557215, src_33557216, ti_33557217) {
  var result_33557226 = null;

    switch (ti_33557217.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer_33557206(ti_33557217))) {
      result_33557226 = src_33557216;
      }
      else {
        result_33557226 = [src_33557216[0], src_33557216[1]];
      }
      
      break;
    case 19:
            if (dest_33557215 === null || dest_33557215 === undefined) {
        dest_33557215 = {};
      }
      else {
        for (var key in dest_33557215) { delete dest_33557215[key]; }
      }
      for (var key in src_33557216) { dest_33557215[key] = src_33557216[key]; }
      result_33557226 = dest_33557215;
    
      break;
    case 18:
    case 17:
      if (!((ti_33557217.base == null))) {
      result_33557226 = nimCopy(dest_33557215, src_33557216, ti_33557217.base);
      }
      else {
      if ((ti_33557217.kind == 17)) {
      result_33557226 = (dest_33557215 === null || dest_33557215 === undefined) ? {m_type: ti_33557217} : dest_33557215;
      }
      else {
        result_33557226 = (dest_33557215 === null || dest_33557215 === undefined) ? {} : dest_33557215;
      }
      }
      nimCopyAux(result_33557226, src_33557216, ti_33557217.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_33557216)) { 
        if(dest_33557215 === null || dest_33557215 === undefined || dest_33557215.length != src_33557216.length) {
          dest_33557215 = new src_33557216.constructor(src_33557216);
        } else {
          dest_33557215.set(src_33557216, 0);
        }
        result_33557226 = dest_33557215;
      } else {
        if (src_33557216 === null) {
          result_33557226 = null;
        }
        else {
          if (dest_33557215 === null || dest_33557215 === undefined || dest_33557215.length != src_33557216.length) {
            dest_33557215 = new Array(src_33557216.length);
          }
          result_33557226 = dest_33557215;
          for (var i = 0; i < src_33557216.length; ++i) {
            result_33557226[i] = nimCopy(result_33557226[i], src_33557216[i], ti_33557217.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_33557216 === null) {
        result_33557226 = null;
      }
      else {
        if (dest_33557215 === null || dest_33557215 === undefined || dest_33557215.length != src_33557216.length) {
          dest_33557215 = new Array(src_33557216.length);
        }
        result_33557226 = dest_33557215;
        for (var i = 0; i < src_33557216.length; ++i) {
          result_33557226[i] = nimCopy(result_33557226[i], src_33557216[i], ti_33557217.base);
        }
      }
    
      break;
    case 28:
            if (src_33557216 !== null) {
        result_33557226 = src_33557216.slice(0);
      }
    
      break;
    default: 
      result_33557226 = src_33557216;
      break;
    }

  return result_33557226;

}

function chckIndx(i_33557263, a_33557264, b_33557265) {
  var result_33557266 = 0;

  BeforeRet: {
    if (((a_33557264 <= i_33557263) && (i_33557263 <= b_33557265))) {
    result_33557266 = i_33557263;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_33557263, a_33557264, b_33557265);
    }
    
  };

  return result_33557266;

}

function makeNimstrLit(c_33556854) {
      var result = [];
  for (var i = 0; i < c_33556854.length; ++i) {
    result[i] = c_33556854.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_33557007, b_33557008) {
        var result = a_33557007 - b_33557008;
    checkOverflowInt(result);
    return result;
  

  
}

function cstrToNimstr(c_33556857) {
      var ln = c_33556857.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_33556857.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_33556857.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}
var ConstSet2 = setConstr([65, 90]);
var ConstSet3 = setConstr(95, 32, 46);
var ConstSet4 = setConstr(95, 32, 46);

function mulInt(a_33557011, b_33557012) {
        var result = a_33557011 * b_33557012;
    checkOverflowInt(result);
    return result;
  

  
}
var ConstSet5 = setConstr([97, 122]);
var ConstSet6 = setConstr([65, 90], [97, 122]);
var ConstSet7 = setConstr([97, 122]);
var ConstSet8 = setConstr([65, 90]);
var ConstSet9 = setConstr([65, 90], [97, 122]);

function nimMax(a_33557061, b_33557062) {
    var Temporary1;

  var result_33557063 = 0;

  BeforeRet: {
    if ((b_33557062 <= a_33557061)) {
    Temporary1 = a_33557061;
    }
    else {
    Temporary1 = b_33557062;
    }
    
    result_33557063 = Temporary1;
    break BeforeRet;
  };

  return result_33557063;

}

function nimMin(a_33557057, b_33557058) {
    var Temporary1;

  var result_33557059 = 0;

  BeforeRet: {
    if ((a_33557057 <= b_33557058)) {
    Temporary1 = a_33557057;
    }
    else {
    Temporary1 = b_33557058;
    }
    
    result_33557059 = Temporary1;
    break BeforeRet;
  };

  return result_33557059;

}

function addChar(x_33557350, c_33557351) {
    x_33557350.push(c_33557351);

  
}
var objectID_1207959723 = [0];

function setTheme(theme_570425350) {
    document.documentElement.setAttribute("data-theme", theme_570425350);
    window.localStorage.setItem("theme", theme_570425350);

  
}

function add_33556392(x_33556393, x_33556393_Idx, y_33556394) {
          if (x_33556393[x_33556393_Idx] === null) { x_33556393[x_33556393_Idx] = []; }
      var off = x_33556393[x_33556393_Idx].length;
      x_33556393[x_33556393_Idx].length += y_33556394.length;
      for (var i = 0; i < y_33556394.length; ++i) {
        x_33556393[x_33556393_Idx][off+i] = y_33556394.charCodeAt(i);
      }
    

  
}

function newSeq_33556878(len_33556880) {
  var result_33556881 = [];

    result_33556881 = new Array(len_33556880); for (var i = 0 ; i < len_33556880 ; ++i) { result_33556881[i] = null; }
  return result_33556881;

}

function unhandledException(e_33556644) {
    var buf_33556645 = [[]];
    if (!(((e_33556644.message).length == 0))) {
    buf_33556645[0].push.apply(buf_33556645[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556645[0].push.apply(buf_33556645[0], e_33556644.message);;
    }
    else {
    buf_33556645[0].push.apply(buf_33556645[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556645[0].push.apply(buf_33556645[0], [32,91]);;
    add_33556392(buf_33556645, 0, e_33556644.name);
    buf_33556645[0].push.apply(buf_33556645[0], [93,10]);;
    var cbuf_33556646 = toJSStr(buf_33556645[0]);
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556646);
  }
  else {
    throw cbuf_33556646;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_33557001) {
        if (a_33557001 > 2147483647 || a_33557001 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function addChars_301990072(result_301990074, result_301990074_Idx, x_301990075, start_301990076, n_301990077) {
    var Temporary1;

    var old_301990078 = (result_301990074[result_301990074_Idx]).length;
    if (result_301990074[result_301990074_Idx].length < (Temporary1 = chckRange(addInt(old_301990078, n_301990077), 0, 2147483647), Temporary1)) { for (var i = result_301990074[result_301990074_Idx].length; i < Temporary1; ++i) result_301990074[result_301990074_Idx].push(0); }
         else {result_301990074[result_301990074_Idx].length = Temporary1; };
    Label2: {
      var iHEX60gensym4_301990092 = 0;
      var i_570426440 = 0;
      Label3: {
          Label4: while (true) {
          if (!(i_570426440 < n_301990077)) break Label4;
            iHEX60gensym4_301990092 = i_570426440;
            result_301990074[result_301990074_Idx][chckIndx(addInt(old_301990078, iHEX60gensym4_301990092), 0, (result_301990074[result_301990074_Idx]).length - 1)] = x_301990075.charCodeAt(chckIndx(addInt(start_301990076, iHEX60gensym4_301990092), 0, (x_301990075).length - 1));
            i_570426440 = addInt(i_570426440, 1);
          }
      };
    };

  
}

function addChars_301990068(result_301990070, result_301990070_Idx, x_301990071) {
    addChars_301990072(result_301990070, result_301990070_Idx, x_301990071, 0, ((x_301990071) == null ? 0 : (x_301990071).length));

  
}

function addInt_301990093(result_301990094, result_301990094_Idx, x_301990095) {
    addChars_301990068(result_301990094, result_301990094_Idx, ((x_301990095) + ""));

  
}

function addInt_301990111(result_301990112, result_301990112_Idx, x_301990113) {
    addInt_301990093(result_301990112, result_301990112_Idx, BigInt(x_301990113));

  
}

function HEX24_385875976(x_385875977) {
  var result_385875978 = [[]];

    addInt_301990111(result_385875978, 0, x_385875977);

  return result_385875978[0];

}

function isFatPointer_33557206(ti_33557207) {
  var result_33557208 = false;

  BeforeRet: {
    result_33557208 = !((ConstSet1[ti_33557207.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557208;

}

function nimCopyAux(dest_33557219, src_33557220, n_33557221) {
    switch (n_33557221.kind) {
    case 0:
      break;
    case 1:
            dest_33557219[n_33557221.offset] = nimCopy(dest_33557219[n_33557221.offset], src_33557220[n_33557221.offset], n_33557221.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_33557221.sons.length; i++) {
      nimCopyAux(dest_33557219, src_33557220, n_33557221.sons[i]);
    }
    
      break;
    case 3:
            dest_33557219[n_33557221.offset] = nimCopy(dest_33557219[n_33557221.offset], src_33557220[n_33557221.offset], n_33557221.typ);
      for (var i = 0; i < n_33557221.sons.length; ++i) {
        nimCopyAux(dest_33557219, src_33557220, n_33557221.sons[i][1]);
      }
    
      break;
    }

  
}

function raiseIndexError(i_33556783, a_33556784, b_33556785) {
    var Temporary1;

    if ((b_33556785 < a_33556784)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24_385875976(i_33556783) || [],[32,110,111,116,32,105,110,32] || [],HEX24_385875976(a_33556784) || [],[32,46,46,32] || [],HEX24_385875976(b_33556785) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function sysFatal_268435498(message_268435501) {
    raiseException({message: nimCopy(null, message_268435501, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");

  
}

function raiseAssert_268435496(msg_268435497) {
    sysFatal_268435498(msg_268435497);

  
}

function failedAssertImpl_268435532(msg_268435533) {
    raiseAssert_268435496(msg_268435533);

  
}

function onDOMLoaded(e_570425379) {
            
function HEX3Aanonymous_570425403(event_570425404) {
                event_570425404.target.parentNode.style.display = "none";
                event_570425404.target.parentNode.nextSibling.style.display = "inline";

              
            }

    document.getElementById("theme-select").value = window.localStorage.getItem("theme");
    Label1: {
      var pragmaDots_570425402 = null;
      var colontmp__570426431 = [];
      colontmp__570426431 = document.getElementsByClassName("pragmadots");
      var i_570426433 = 0;
      var L_570426434 = (colontmp__570426431).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426433 < L_570426434)) break Label3;
            pragmaDots_570425402 = colontmp__570426431[chckIndx(i_570426433, 0, (colontmp__570426431).length - 1)];
            pragmaDots_570425402.onclick = HEX3Aanonymous_570425403;
            i_570426433 = addInt(i_570426433, 1);
            if (!(((colontmp__570426431).length == L_570426434))) {
            failedAssertImpl_268435532(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };

  
}

function isWhitespace_570425714(x_570425715) {
  var result_570425716 = false;

    result_570425716 = (((x_570425715.nodeName == "#text") && !/\S/.test(x_570425715.textContent)) || (x_570425715.nodeName == "#comment"));

  return result_570425716;

}

function toToc_570425717(x_570425718, father_570425719) {
                var Temporary5;
            var Temporary6;
            var Temporary7;
            var Temporary8;
      var Temporary15;

    if ((x_570425718.nodeName == "UL")) {
    var f_570425727 = {heading: null, kids: [], sortId: (father_570425719.kids).length, doSort: false};
    var i_570425728 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_570425728 < x_570425718.childNodes.length)) break Label2;
          var nxt_570425729 = addInt(i_570425728, 1);
          Label3: {
              Label4: while (true) {
                if (!(nxt_570425729 < x_570425718.childNodes.length)) Temporary5 = false; else {                  Temporary5 = isWhitespace_570425714(x_570425718.childNodes[nxt_570425729]);                }              if (!Temporary5) break Label4;
                nxt_570425729 = addInt(nxt_570425729, 1);
              }
          };
            if (!(nxt_570425729 < x_570425718.childNodes.length)) Temporary8 = false; else {              Temporary8 = (x_570425718.childNodes[i_570425728].nodeName == "LI");            }            if (!Temporary8) Temporary7 = false; else {              Temporary7 = (x_570425718.childNodes[i_570425728].childNodes.length == 1);            }            if (!Temporary7) Temporary6 = false; else {              Temporary6 = (x_570425718.childNodes[nxt_570425729].nodeName == "UL");            }          if (Temporary6) {
          var e_570425742 = {heading: x_570425718.childNodes[i_570425728].childNodes[0], kids: [], sortId: (f_570425727.kids).length, doSort: false};
          var it_570425743 = x_570425718.childNodes[nxt_570425729];
          Label9: {
            var j_570425748 = 0;
            var colontmp__570426447 = 0;
            colontmp__570426447 = it_570425743.childNodes.length;
            var i_570426448 = 0;
            Label10: {
                Label11: while (true) {
                if (!(i_570426448 < colontmp__570426447)) break Label11;
                  j_570425748 = i_570426448;
                  toToc_570425717(it_570425743.childNodes[j_570425748], e_570425742);
                  i_570426448 = addInt(i_570426448, 1);
                }
            };
          };
          f_570425727.kids.push(e_570425742);;
          i_570425728 = addInt(nxt_570425729, 1);
          }
          else {
            toToc_570425717(x_570425718.childNodes[i_570425728], f_570425727);
            i_570425728 = addInt(i_570425728, 1);
          }
          
        }
    };
    father_570425719.kids.push(f_570425727);;
    }
    else {
    if (isWhitespace_570425714(x_570425718)) {
    }
    else {
    if ((x_570425718.nodeName == "LI")) {
    var idx_570425766 = [];
    Label12: {
      var i_570425771 = 0;
      var colontmp__570426451 = 0;
      colontmp__570426451 = x_570425718.childNodes.length;
      var i_570426452 = 0;
      Label13: {
          Label14: while (true) {
          if (!(i_570426452 < colontmp__570426451)) break Label14;
            i_570425771 = i_570426452;
            if (!(isWhitespace_570425714(x_570425718.childNodes[i_570425771]))) {
            idx_570425766.push(i_570425771);;
            }
            
            i_570426452 = addInt(i_570426452, 1);
          }
      };
    };
      if (!((idx_570425766).length == 2)) Temporary15 = false; else {        Temporary15 = (x_570425718.childNodes[idx_570425766[chckIndx(1, 0, (idx_570425766).length - 1)]].nodeName == "UL");      }    if (Temporary15) {
    var e_570425787 = {heading: x_570425718.childNodes[idx_570425766[chckIndx(0, 0, (idx_570425766).length - 1)]], kids: [], sortId: (father_570425719.kids).length, doSort: false};
    var it_570425788 = x_570425718.childNodes[idx_570425766[chckIndx(1, 0, (idx_570425766).length - 1)]];
    Label16: {
      var j_570425793 = 0;
      var colontmp__570426455 = 0;
      colontmp__570426455 = it_570425788.childNodes.length;
      var i_570426456 = 0;
      Label17: {
          Label18: while (true) {
          if (!(i_570426456 < colontmp__570426455)) break Label18;
            j_570425793 = i_570426456;
            toToc_570425717(it_570425788.childNodes[j_570425793], e_570425787);
            i_570426456 = addInt(i_570426456, 1);
          }
      };
    };
    father_570425719.kids.push(e_570425787);;
    }
    else {
      Label19: {
        var i_570425802 = 0;
        var colontmp__570426459 = 0;
        colontmp__570426459 = x_570425718.childNodes.length;
        var i_570426460 = 0;
        Label20: {
            Label21: while (true) {
            if (!(i_570426460 < colontmp__570426459)) break Label21;
              i_570425802 = i_570426460;
              toToc_570425717(x_570425718.childNodes[i_570425802], father_570425719);
              i_570426460 = addInt(i_570426460, 1);
            }
        };
      };
    }
    
    }
    else {
    father_570425719.kids.push({heading: x_570425718, kids: [], sortId: (father_570425719.kids).length, doSort: false});;
    }
    }}

  
}

function extractItems_570425525(x_570425526, heading_570425527, items_570425528, items_570425528_Idx) {
  BeforeRet: {
    if ((x_570425526 == null)) {
    break BeforeRet;
    }
    
    if ((!((x_570425526.heading == null)) && (x_570425526.heading.textContent == heading_570425527))) {
    Label1: {
      var i_570425545 = 0;
      var colontmp__570426463 = 0;
      colontmp__570426463 = (x_570425526.kids).length;
      var i_570426464 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426464 < colontmp__570426463)) break Label3;
            i_570425545 = i_570426464;
            items_570425528[items_570425528_Idx].push(x_570425526.kids[chckIndx(i_570425545, 0, (x_570425526.kids).length - 1)].heading);;
            i_570426464 = addInt(i_570426464, 1);
          }
      };
    };
    }
    else {
      Label4: {
        var k_570425571 = null;
        var i_570426468 = 0;
        var L_570426469 = (x_570425526.kids).length;
        Label5: {
            Label6: while (true) {
            if (!(i_570426468 < L_570426469)) break Label6;
              k_570425571 = x_570425526.kids[chckIndx(i_570426468, 0, (x_570425526.kids).length - 1)];
              extractItems_570425525(k_570425571, heading_570425527, items_570425528, items_570425528_Idx);
              i_570426468 = addInt(i_570426468, 1);
              if (!(((x_570425526.kids).length == L_570426469))) {
              failedAssertImpl_268435532(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
              }
              
            }
        };
      };
    }
    
  };

  
}

function tree_570425456(tag_570425457, kids_570425458) {
  var result_570425459 = null;

    result_570425459 = document.createElement(tag_570425457);
    Label1: {
      var k_570425473 = null;
      var i_570426481 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426481 < (kids_570425458).length)) break Label3;
            k_570425473 = kids_570425458[chckIndx(i_570426481, 0, (kids_570425458).length - 1)];
            result_570425459.appendChild(k_570425473);
            i_570426481 = addInt(i_570426481, 1);
          }
      };
    };

  return result_570425459;

}

function text_570425481(s_570425482) {
  var result_570425483 = null;

    result_570425483 = document.createTextNode(s_570425482);

  return result_570425483;

}

function uncovered_570425891(x_570425892) {
    var Temporary1;

  var result_570425893 = null;

  BeforeRet: {
    if ((((x_570425892.kids).length == 0) && !((x_570425892.heading == null)))) {
    if (!(x_570425892.heading.hasOwnProperty('__karaxMarker__'))) {
    Temporary1 = x_570425892;
    }
    else {
    Temporary1 = null;
    }
    
    result_570425893 = Temporary1;
    break BeforeRet;
    }
    
    result_570425893 = {heading: x_570425892.heading, kids: [], sortId: x_570425892.sortId, doSort: x_570425892.doSort};
    Label2: {
      var k_570425908 = null;
      var i_570426488 = 0;
      var L_570426489 = (x_570425892.kids).length;
      Label3: {
          Label4: while (true) {
          if (!(i_570426488 < L_570426489)) break Label4;
            k_570425908 = x_570425892.kids[chckIndx(i_570426488, 0, (x_570425892.kids).length - 1)];
            var y_570425909 = uncovered_570425891(k_570425908);
            if (!((y_570425909 == null))) {
            result_570425893.kids.push(y_570425909);;
            }
            
            i_570426488 = addInt(i_570426488, 1);
            if (!(((x_570425892.kids).length == L_570426489))) {
            failedAssertImpl_268435532(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (((result_570425893.kids).length == 0)) {
    result_570425893 = null;
    }
    
  };

  return result_570425893;

}

function mergeTocs_570425921(orig_570425922, news_570425923) {
  var result_570425924 = null;

    result_570425924 = uncovered_570425891(orig_570425922);
    if ((result_570425924 == null)) {
    result_570425924 = news_570425923;
    }
    else {
      Label1: {
        var i_570425936 = 0;
        var colontmp__570426484 = 0;
        colontmp__570426484 = (news_570425923.kids).length;
        var i_570426485 = 0;
        Label2: {
            Label3: while (true) {
            if (!(i_570426485 < colontmp__570426484)) break Label3;
              i_570425936 = i_570426485;
              result_570425924.kids.push(news_570425923.kids[chckIndx(i_570425936, 0, (news_570425923.kids).length - 1)]);;
              i_570426485 = addInt(i_570426485, 1);
            }
        };
      };
    }
    

  return result_570425924;

}

function buildToc_570425941(orig_570425942, types_570425943, procs_570425944) {
  var result_570425945 = null;

    var newStuff_570425950 = {heading: null, kids: [], doSort: true, sortId: 0};
    Label1: {
      var t_570425954 = null;
      var i_570426476 = 0;
      var L_570426477 = (types_570425943).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426476 < L_570426477)) break Label3;
            t_570425954 = types_570425943[chckIndx(i_570426476, 0, (types_570425943).length - 1)];
            var c_570425959 = {heading: t_570425954.cloneNode(true), kids: [], doSort: true, sortId: 0};
            t_570425954.__karaxMarker__ = true;
            Label4: {
              var p_570425963 = null;
              var i_570426473 = 0;
              var L_570426474 = (procs_570425944).length;
              Label5: {
                  Label6: while (true) {
                  if (!(i_570426473 < L_570426474)) break Label6;
                    p_570425963 = procs_570425944[chckIndx(i_570426473, 0, (procs_570425944).length - 1)];
                    if (!(p_570425963.hasOwnProperty('__karaxMarker__'))) {
                    var xx_570425964 = p_570425963.parentNode.getElementsByClassName("attachedType");
                    if ((((xx_570425964).length == 1) && (xx_570425964[chckIndx(0, 0, (xx_570425964).length - 1)].textContent == t_570425954.textContent))) {
                    var q_570425969 = tree_570425456("A", [text_570425481(p_570425963.title)]);
                    q_570425969.setAttribute("href", p_570425963.getAttribute("href"));
                    c_570425959.kids.push({heading: q_570425969, kids: [], sortId: 0, doSort: false});;
                    p_570425963.__karaxMarker__ = true;
                    }
                    
                    }
                    
                    i_570426473 = addInt(i_570426473, 1);
                    if (!(((procs_570425944).length == L_570426474))) {
                    failedAssertImpl_268435532(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
                    }
                    
                  }
              };
            };
            newStuff_570425950.kids.push(c_570425959);;
            i_570426476 = addInt(i_570426476, 1);
            if (!(((types_570425943).length == L_570426477))) {
            failedAssertImpl_268435532(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_570425945 = mergeTocs_570425921(orig_570425942, newStuff_570425950);

  return result_570425945;

}

function add_570425474(parent_570425475, kid_570425476) {
    if (((parent_570425475.nodeName == "TR") && ((kid_570425476.nodeName == "TD") || (kid_570425476.nodeName == "TH")))) {
    var k_570425477 = document.createElement("TD");
    k_570425477.appendChild(kid_570425476);
    parent_570425475.appendChild(k_570425477);
    }
    else {
    parent_570425475.appendChild(kid_570425476);
    }
    

  
}

function setClass_570425478(e_570425479, value_570425480) {
    e_570425479.setAttribute("class", value_570425480);

  
}

function toHtml_570425598(x_570425599, isRoot_570425600) {
    
function HEX3Aanonymous_570425618(a_570425619, b_570425620) {
      var result_570425621 = 0;

      BeforeRet: {
        if ((!((a_570425619.heading == null)) && !((b_570425620.heading == null)))) {
        var x_570425630 = a_570425619.heading.textContent;
        var y_570425631 = b_570425620.heading.textContent;
        if ((x_570425630 < y_570425631)) {
        result_570425621 = -1;
        break BeforeRet;
        }
        
        if ((y_570425631 < x_570425630)) {
        result_570425621 = 1;
        break BeforeRet;
        }
        
        result_570425621 = 0;
        break BeforeRet;
        }
        else {
          result_570425621 = subInt(a_570425619.sortId, b_570425620.sortId);
          break BeforeRet;
        }
        
      };

      return result_570425621;

    }

  var result_570425601 = null;

  BeforeRet: {
    if ((x_570425599 == null)) {
    result_570425601 = null;
    break BeforeRet;
    }
    
    if (((x_570425599.kids).length == 0)) {
    if ((x_570425599.heading == null)) {
    result_570425601 = null;
    break BeforeRet;
    }
    
    result_570425601 = x_570425599.heading.cloneNode(true);
    break BeforeRet;
    }
    
    result_570425601 = tree_570425456("DIV", []);
    if ((!((x_570425599.heading == null)) && !(x_570425599.heading.hasOwnProperty('__karaxMarker__')))) {
    add_570425474(result_570425601, x_570425599.heading.cloneNode(true));
    }
    
    var ul_570425617 = tree_570425456("UL", []);
    if (isRoot_570425600) {
    setClass_570425478(ul_570425617, "simple simple-toc");
    }
    else {
    setClass_570425478(ul_570425617, "simple");
    }
    
    if (x_570425599.doSort) {
    x_570425599.kids.sort(HEX3Aanonymous_570425618);
    }
    
    Label1: {
      var k_570425643 = null;
      var i_570426492 = 0;
      var L_570426493 = (x_570425599.kids).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426492 < L_570426493)) break Label3;
            k_570425643 = x_570425599.kids[chckIndx(i_570426492, 0, (x_570425599.kids).length - 1)];
            var y_570425644 = toHtml_570425598(k_570425643, false);
            if (!((y_570425644 == null))) {
            add_570425474(ul_570425617, tree_570425456("LI", [y_570425644]));
            }
            
            i_570426492 = addInt(i_570426492, 1);
            if (!(((x_570425599.kids).length == L_570426493))) {
            failedAssertImpl_268435532(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    if (!((ul_570425617.childNodes.length == 0))) {
    add_570425474(result_570425601, ul_570425617);
    }
    
    if ((result_570425601.childNodes.length == 0)) {
    result_570425601 = null;
    }
    
  };

  return result_570425601;

}

function replaceById_570425484(id_570425485, newTree_570425486) {
    var x_570425487 = document.getElementById(id_570425485);
    x_570425487.parentNode.replaceChild(newTree_570425486, x_570425487);
    newTree_570425486.id = id_570425485;

  
}

function togglevis_570425996(d_570425997) {
    if ((d_570425997.style.display == "none")) {
    d_570425997.style.display = "inline";
    }
    else {
      d_570425997.style.display = "none";
    }
    

  
}

function groupBy(value_570425999) {
    var toc_570426000 = document.getElementById("toc-list");
    if ((alternative_570425995[0] == null)) {
    var tt_570426008 = {heading: null, kids: [], sortId: 0, doSort: false};
    toToc_570425717(toc_570426000, tt_570426008);
    tt_570426008 = tt_570426008.kids[chckIndx(0, 0, (tt_570426008.kids).length - 1)];
    var types_570426013 = [[]];
    var procs_570426018 = [[]];
    extractItems_570425525(tt_570426008, "Types", types_570426013, 0);
    extractItems_570425525(tt_570426008, "Procs", procs_570426018, 0);
    extractItems_570425525(tt_570426008, "Converters", procs_570426018, 0);
    extractItems_570425525(tt_570426008, "Methods", procs_570426018, 0);
    extractItems_570425525(tt_570426008, "Templates", procs_570426018, 0);
    extractItems_570425525(tt_570426008, "Macros", procs_570426018, 0);
    extractItems_570425525(tt_570426008, "Iterators", procs_570426018, 0);
    var ntoc_570426019 = buildToc_570425941(tt_570426008, types_570426013[0], procs_570426018[0]);
    var x_570426020 = toHtml_570425598(ntoc_570426019, true);
    alternative_570425995[0] = tree_570425456("DIV", [x_570426020]);
    }
    
    if ((value_570425999 == "type")) {
    replaceById_570425484("tocRoot", alternative_570425995[0]);
    }
    else {
    replaceById_570425484("tocRoot", tree_570425456("DIV", []));
    }
    
    togglevis_570425996(document.getElementById("toc-list"));

  
}

function HEX5BHEX5D_738198812(s_738198815, x_738198816) {
  var result_738198817 = [];

    var a_738198819 = x_738198816.a;
    var L_738198821 = addInt(subInt(subInt((s_738198815).length, x_738198816.b), a_738198819), 1);
    result_738198817 = nimCopy(null, mnewString(chckRange(L_738198821, 0, 2147483647)), NTI33554449);
    Label1: {
      var i_738198826 = 0;
      var i_570426502 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426502 < L_738198821)) break Label3;
            i_738198826 = i_570426502;
            result_738198817[chckIndx(i_738198826, 0, (result_738198817).length - 1)] = s_738198815[chckIndx(addInt(i_738198826, a_738198819), 0, (s_738198815).length - 1)];
            i_570426502 = addInt(i_570426502, 1);
          }
      };
    };

  return result_738198817;

}

function HEX2EHEX2E_973078628(a_973078631, b_973078632) {
  var result_973078635 = ({a: 0, b: 0});

    result_973078635 = nimCopy(result_973078635, {a: a_973078631, b: b_973078632}, NTI973078614);

  return result_973078635;

}
async function loadIndex_570426194() {
  var result_570426196 = null;

  BeforeRet: {
    var indexURL_570426202 = document.getElementById("indexLink").getAttribute("href");
    var rootURL_570426228 = HEX5BHEX5D_738198812(cstrToNimstr(indexURL_570426202), HEX2EHEX2E_973078628(0, 14));
    var resp_570426240 = (await (await fetch(indexURL_570426202)).text());
    var indexElem_570426241 = document.createElement("div");
    indexElem_570426241.innerHTML = resp_570426240;
    Label1: {
      var href_570426263 = null;
      var colontmp__570426496 = [];
      colontmp__570426496 = indexElem_570426241.getElementsByClassName("reference");
      var i_570426498 = 0;
      var L_570426499 = (colontmp__570426496).length;
      Label2: {
          Label3: while (true) {
          if (!(i_570426498 < L_570426499)) break Label3;
            href_570426263 = colontmp__570426496[chckIndx(i_570426498, 0, (colontmp__570426496).length - 1)];
            href_570426263.setAttribute("href", toJSStr((rootURL_570426228 || []).concat(cstrToNimstr(href_570426263.getAttribute("href")) || [])));
            db_570426034[0].push(href_570426263);;
            contents_570426035[0].push(href_570426263.getAttribute("data-doc-search-tag"));;
            i_570426498 = addInt(i_570426498, 1);
            if (!(((colontmp__570426496).length == L_570426499))) {
            failedAssertImpl_268435532(makeNimstrLit("iterators.nim(246, 11) `len(a) == L` the length of the seq changed while iterating over it"));
            }
            
          }
      };
    };
    result_570426196 = undefined;
    break BeforeRet;
  };

  return result_570426196;

}

function then_570426357(future_570426360, onSuccess_570426361, onReject_570426362) {
  var result_570426363 = null;

  BeforeRet: {
    var ret_570426373 = null;
    ret_570426373 = future_570426360.then(onSuccess_570426361, onReject_570426362)
    result_570426363 = ret_570426373;
    break BeforeRet;
  };

  return result_570426363;

}

function nsuToLowerAsciiChar(c_738197589) {
  var result_738197590 = 0;

    if ((ConstSet2[c_738197589] != undefined)) {
    result_738197590 = (c_738197589 ^ 32);
    }
    else {
      result_738197590 = c_738197589;
    }
    

  return result_738197590;

}

function fuzzyMatch_721420304(pattern_721420305, str_721420306) {
              var Temporary4;
              var Temporary5;
                var Temporary6;
      var Temporary7;
        var Temporary8;

  var result_721420309 = {Field0: 0, Field1: false};

    var scoreState_721420310 = -100;
    var headerMatched_721420311 = false;
    var unmatchedLeadingCharCount_721420312 = 0;
    var consecutiveMatchCount_721420313 = 0;
    var strIndex_721420314 = 0;
    var patIndex_721420315 = 0;
    var score_721420316 = 0;
    Label1: {
        Label2: while (true) {
        if (!((strIndex_721420314 < ((str_721420306) == null ? 0 : (str_721420306).length)) && (patIndex_721420315 < ((pattern_721420305) == null ? 0 : (pattern_721420305).length)))) break Label2;
          Label3: {
            var patternChar_721420319 = nsuToLowerAsciiChar(pattern_721420305.charCodeAt(chckIndx(patIndex_721420315, 0, (pattern_721420305).length - 1)));
            var strChar_721420320 = nsuToLowerAsciiChar(str_721420306.charCodeAt(chckIndx(strIndex_721420314, 0, (str_721420306).length - 1)));
            if ((ConstSet3[patternChar_721420319] != undefined)) {
            patIndex_721420315 = addInt(patIndex_721420315, 1);
            break Label3;
            }
            
            if ((ConstSet4[strChar_721420320] != undefined)) {
            strIndex_721420314 = addInt(strIndex_721420314, 1);
            break Label3;
            }
            
            if ((!(headerMatched_721420311) && (strChar_721420320 == 58))) {
            headerMatched_721420311 = true;
            scoreState_721420310 = -100;
            score_721420316 = ((Math.floor((0.5 * score_721420316))) | 0);
            patIndex_721420315 = 0;
            strIndex_721420314 = addInt(strIndex_721420314, 1);
            break Label3;
            }
            
            if ((strChar_721420320 == patternChar_721420319)) {
            switch (scoreState_721420310) {
            case -100:
            case 20:
              scoreState_721420310 = 10;
              break;
            case 0:
              scoreState_721420310 = 5;
              score_721420316 = addInt(score_721420316, scoreState_721420310);
              break;
            case 10:
            case 5:
              consecutiveMatchCount_721420313 = addInt(consecutiveMatchCount_721420313, 1);
              scoreState_721420310 = 5;
              score_721420316 = addInt(score_721420316, mulInt(5, consecutiveMatchCount_721420313));
              if ((scoreState_721420310 == 10)) {
              score_721420316 = addInt(score_721420316, 10);
              }
              
              var onBoundary_721420372 = (patIndex_721420315 == ((pattern_721420305) == null ? -1 : (pattern_721420305).length - 1));
              if ((!(onBoundary_721420372) && (strIndex_721420314 < ((str_721420306) == null ? -1 : (str_721420306).length - 1)))) {
              var nextPatternChar_721420373 = nsuToLowerAsciiChar(pattern_721420305.charCodeAt(chckIndx(addInt(patIndex_721420315, 1), 0, (pattern_721420305).length - 1)));
              var nextStrChar_721420374 = nsuToLowerAsciiChar(str_721420306.charCodeAt(chckIndx(addInt(strIndex_721420314, 1), 0, (str_721420306).length - 1)));
              if (!!((ConstSet5[nextStrChar_721420374] != undefined))) Temporary4 = false; else {                Temporary4 = !((nextStrChar_721420374 == nextPatternChar_721420373));              }              onBoundary_721420372 = Temporary4;
              }
              
              if (onBoundary_721420372) {
              scoreState_721420310 = 20;
              score_721420316 = addInt(score_721420316, scoreState_721420310);
              }
              
              break;
            case -1:
            case -3:
              if (!((ConstSet6[str_721420306.charCodeAt(chckIndx(subInt(strIndex_721420314, 1), 0, (str_721420306).length - 1))] != undefined))) Temporary5 = true; else {                if (!(ConstSet7[str_721420306.charCodeAt(chckIndx(subInt(strIndex_721420314, 1), 0, (str_721420306).length - 1))] != undefined)) Temporary6 = false; else {                  Temporary6 = (ConstSet8[str_721420306.charCodeAt(chckIndx(strIndex_721420314, 0, (str_721420306).length - 1))] != undefined);                }                Temporary5 = Temporary6;              }              var isLeadingChar_721420398 = Temporary5;
              if (isLeadingChar_721420398) {
              scoreState_721420310 = 10;
              }
              else {
                scoreState_721420310 = 0;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
              }
              
              break;
            }
            patIndex_721420315 = addInt(patIndex_721420315, 1);
            }
            else {
              switch (scoreState_721420310) {
              case -100:
                scoreState_721420310 = -3;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
                break;
              case 5:
                scoreState_721420310 = -1;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
                consecutiveMatchCount_721420313 = 0;
                break;
              case -3:
                if ((unmatchedLeadingCharCount_721420312 < 3)) {
                scoreState_721420310 = -3;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
                }
                
                unmatchedLeadingCharCount_721420312 = addInt(unmatchedLeadingCharCount_721420312, 1);
                break;
              default: 
                scoreState_721420310 = -1;
                score_721420316 = addInt(score_721420316, scoreState_721420310);
                break;
              }
            }
            
            strIndex_721420314 = addInt(strIndex_721420314, 1);
          };
        }
    };
      if (!(patIndex_721420315 == ((pattern_721420305) == null ? 0 : (pattern_721420305).length))) Temporary7 = false; else {        if ((strIndex_721420314 == ((str_721420306) == null ? 0 : (str_721420306).length))) Temporary8 = true; else {          Temporary8 = !((ConstSet9[str_721420306.charCodeAt(chckIndx(strIndex_721420314, 0, (str_721420306).length - 1))] != undefined));        }        Temporary7 = Temporary8;      }    if (Temporary7) {
    score_721420316 = addInt(score_721420316, 10);
    }
    
    var colontmp__570426515 = nimMax(0, score_721420316);
    var colontmp__570426516 = (0 < score_721420316);
    result_721420309 = nimCopy(result_721420309, {Field0: colontmp__570426515, Field1: colontmp__570426516}, NTI721420302);

  return result_721420309;

}

function escapeCString_570426036(x_570426037, x_570426037_Idx) {
    var s_570426038 = [];
    Label1: {
      var c_570426039 = 0;
      var iHEX60gensym6_570426519 = 0;
      var nHEX60gensym6_570426520 = ((x_570426037[x_570426037_Idx]) == null ? 0 : (x_570426037[x_570426037_Idx]).length);
      Label2: {
          Label3: while (true) {
          if (!(iHEX60gensym6_570426519 < nHEX60gensym6_570426520)) break Label3;
            c_570426039 = x_570426037[x_570426037_Idx].charCodeAt(chckIndx(iHEX60gensym6_570426519, 0, (x_570426037[x_570426037_Idx]).length - 1));
            switch (c_570426039) {
            case 60:
              s_570426038.push.apply(s_570426038, [38,108,116,59]);;
              break;
            case 62:
              s_570426038.push.apply(s_570426038, [38,103,116,59]);;
              break;
            default: 
              addChar(s_570426038, c_570426039);;
              break;
            }
            iHEX60gensym6_570426519 = addInt(iHEX60gensym6_570426519, 1);
          }
      };
    };
    x_570426037[x_570426037_Idx] = toJSStr(s_570426038);

  
}

function dosearch_570426040(value_570426041) {
    
function HEX3Aanonymous_570426068(a_570426073, b_570426074) {
      var result_570426079 = 0;

        result_570426079 = subInt(b_570426074["Field1"], a_570426073["Field1"]);

      return result_570426079;

    }

  var result_570426042 = null;

  BeforeRet: {
    if (((db_570426034[0]).length == 0)) {
    break BeforeRet;
    }
    
    var ul_570426046 = tree_570425456("UL", []);
    result_570426042 = tree_570425456("DIV", []);
    setClass_570425478(result_570426042, "search_results");
    var matches_570426051 = [];
    Label1: {
      var i_570426059 = 0;
      var colontmp__570426506 = 0;
      colontmp__570426506 = (db_570426034[0]).length;
      var i_570426507 = 0;
      Label2: {
          Label3: while (true) {
          if (!(i_570426507 < colontmp__570426506)) break Label3;
            i_570426059 = i_570426507;
            Label4: {
              var c_570426060 = contents_570426035[0][chckIndx(i_570426059, 0, (contents_570426035[0]).length - 1)];
              if (((c_570426060 == "Examples") || (c_570426060 == "PEG construction"))) {
              break Label4;
              }
              
              var tmpTuple_570426061 = fuzzyMatch_721420304(value_570426041, c_570426060);
              var score_570426062 = tmpTuple_570426061["Field0"];
              var matched_570426063 = tmpTuple_570426061["Field1"];
              if (matched_570426063) {
              matches_570426051.push({Field0: db_570426034[0][chckIndx(i_570426059, 0, (db_570426034[0]).length - 1)], Field1: score_570426062});;
              }
              
            };
            i_570426507 = addInt(i_570426507, 1);
          }
      };
    };
    matches_570426051.sort(HEX3Aanonymous_570426068);
    Label5: {
      var i_570426096 = 0;
      var colontmp__570426510 = 0;
      colontmp__570426510 = nimMin((matches_570426051).length, 29);
      var i_570426511 = 0;
      Label6: {
          Label7: while (true) {
          if (!(i_570426511 < colontmp__570426510)) break Label7;
            i_570426096 = i_570426511;
            matches_570426051[chckIndx(i_570426096, 0, (matches_570426051).length - 1)]["Field0"].innerHTML = matches_570426051[chckIndx(i_570426096, 0, (matches_570426051).length - 1)]["Field0"].getAttribute("data-doc-search-tag");
            escapeCString_570426036(matches_570426051[chckIndx(i_570426096, 0, (matches_570426051).length - 1)]["Field0"], "innerHTML");
            add_570425474(ul_570426046, tree_570425456("LI", [matches_570426051[chckIndx(i_570426096, 0, (matches_570426051).length - 1)]["Field0"]]));
            i_570426511 = addInt(i_570426511, 1);
          }
      };
    };
    if ((ul_570426046.childNodes.length == 0)) {
    add_570425474(result_570426042, tree_570425456("B", [text_570425481("no search results")]));
    }
    else {
      add_570425474(result_570426042, tree_570425456("B", [text_570425481("search results")]));
      add_570425474(result_570426042, ul_570426046);
    }
    
  };

  return result_570426042;

}

function search() {
    
function wrapper_570426342() {
        var elem_570426343 = document.getElementById("searchInput");
        var value_570426344 = elem_570426343.value;
        if (!((((value_570426344) == null ? 0 : (value_570426344).length) == 0))) {
        if ((oldtoc_570426337[0] == null)) {
        oldtoc_570426337[0] = document.getElementById("tocRoot");
        }
        
        var results_570426348 = dosearch_570426040(value_570426344);
        replaceById_570425484("tocRoot", results_570426348);
        }
        else {
        if (!((oldtoc_570426337[0] == null))) {
        replaceById_570425484("tocRoot", oldtoc_570426337[0]);
        }
        }

      
    }

    if ((loadIndexFut_570426340[0] == null)) {
    loadIndexFut_570426340[0] = loadIndex_570426194();
    var _ = then_570426357(loadIndexFut_570426340[0], wrapper_570426342, null);
    }
    
    if (!((timer_570426338[0] == null))) {
    clearTimeout(timer_570426338[0]);
    }
    
    timer_570426338[0] = setTimeout(wrapper_570426342, 400);

  
}

function copyToClipboard() {
    
    function updatePreTags() {

      const allPreTags = document.querySelectorAll("pre")
    
      allPreTags.forEach((e) => {
      
          const div = document.createElement("div")
          div.classList.add("copyToClipBoard")
    
          const preTag = document.createElement("pre")
          preTag.innerHTML = e.innerHTML
    
          const button = document.createElement("button")
          button.value = e.textContent.replace('...', '') 
          button.classList.add("copyToClipBoardBtn")
          button.style.cursor = "pointer"
    
          div.appendChild(preTag)
          div.appendChild(button)
    
          e.outerHTML = div.outerHTML
      
      })
    }


    function copyTextToClipboard(e) {
        const clipBoardContent = e.target.value
        navigator.clipboard.writeText(clipBoardContent).then(function() {
            e.target.style.setProperty("--clipboard-image", "var(--clipboard-image-selected)")
        }, function(err) {
            console.error("Could not copy text: ", err);
        });
    }

    window.addEventListener("click", (e) => {
        if (e.target.classList.contains("copyToClipBoardBtn")) {
            copyTextToClipboard(e)
          }
    })

    window.addEventListener("mouseover", (e) => {
        if (e.target.nodeName === "PRE") {
            e.target.nextElementSibling.style.setProperty("--clipboard-image", "var(--clipboard-image-normal)")
        }
    })
    
    window.addEventListener("DOMContentLoaded", updatePreTags)

    

  
}
var Temporary1;
var t_570425377 = window.localStorage.getItem("theme");
if ((t_570425377 == null)) {
Temporary1 = "auto";
}
else {
Temporary1 = t_570425377;
}

setTheme(Temporary1);
var alternative_570425995 = [null];
var db_570426034 = [[]];
var contents_570426035 = [[]];
var oldtoc_570426337 = [null];
var timer_570426338 = [null];
var loadIndexFut_570426340 = [null];
copyToClipboard();
window.addEventListener("DOMContentLoaded", onDOMLoaded, false);
